### ISSUE TITLE
Items disappearing/deleting when entering system or using the fill recipe button 

### ISSUE THREAD

**Issue by DMCK96** [badasintended/slotlink#101]
**Setup**
- Minecraft: 1.17.1
- Fabric API: 0.37.2+1.17
- slotlink: 3.0.9
- related mod: All of Fabric 4 Pack (potentially craftingtweaks-fabric-13.0.0+0)

**Problem**
When inserting items via the Storage Request table items will just disappear sporadically. I have checked every connected inventory and checked the server logs for any errors. 

**Reproduction**
![2021-08-11_20 35 40](https://user-images.githubusercontent.com/26749858/129092048-4db92410-004e-42ce-bc9a-a6ed07fc15dd.png)
Sporadically when inserting multiple full stacks, it also happens when using craft to grid from REI (+ sign in bottom right of recipe) and you swap between recipes without clearing the crafting grid.

**Remarks**
The craft to grid is the more reliable way of reproducing, it also seems to be happening more to iron ingots than any other item.

**Comment by deirn** [comment]
I'm not noticing items getting voided, but I did notice that the count is not correctly updated. Can you try [this](https://github.com/badasintended/slotlink/suites/3477737953/artifacts/82713251) and see if the issue persists? Use the jar with no `-dev` suffix.

**Comment by DMCK96** [comment]
I've not been able to reproduce this bug with that fix. I'll keep monitoring over the next couple of days and if it occurs again I shall let you know.

**Comment by DMCK96** [comment]
After 3-4 hours of playtime I haven't seen this issue reoccur.
