### ISSUE TITLE
Items disappear

### ISSUE THREAD

**Issue by johannesmateboer** [badasintended/slotlink#103]
**Setup**
- Minecraft: 1.17.1
- Fabric API: 0.37.2
- slotlink: 3.0.9 and 3.0.10
- related mod: Maybe Mouse Wheelie (https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie)

**Problem**
Items disappear. See attached video for an example. It happens in the following situations:
- When Shift-moving items from inventory to slotlink (as shown in video)
- Shift-clicking craft-results in the crafting-grid. They disappear as in: not stored in storage.

Crash report: No crash, but video: https://mega.nz/file/2vgS3QJQ#AH4byrFzb-2SRtN4RFqJQb0LIKRUmpaSsgdt2ZZlAac

**Reproduction**
See video

**Remarks**
- The slotlink-setup used is large. Storage is done by 8 netherchests (158 stacks each)
- The Shift-moving option is added by Mouse Wheelie

**Comment by johannesmateboer** [comment]
In addition: items left in the crafting-grid when closed will remove them.

**Comment by deirn** [comment]
Does it happen without mouse wheelie?

**Comment by johannesmateboer** [comment]
Been testing with some different mods disabled/enabled. Without mousewheelie it appears to have no problems so far.

**Comment by deirn** [comment]
Hmm this is hard to debug 😞. I could only get reproduce it once...

**Comment by johannesmateboer** [comment]
I found a way to reproduce it:

1. Open the Storage Request
2. Hold an item in your hand
3. Close the Storage Request

Now the item held is gone. So if you hold a crafting-result and close the SR, the crafting result is gone.

**Comment by johannesmateboer** [comment]
Video in action:
https://mega.nz/file/Wug2yDJA#fDSz1EOFYpVEvuyiIWxJl5PZvV60R3y9S7VBddlHZ5s

**Comment by augustoeliezer** [comment]
Same problem, when I crafting something and use REI to crafting some missing item, I lost one item.

Eg: red_bits:timer needs 4x minecraft:redstone torch nad 3x minecraft:stone

1. I use REI to try craft and check I need more 1 redstone torch.
2. I use REI again to craft more one redstone torch
3. When I use REI to craft the timer still needing a redstone toch

**Comment by deirn** [comment]
@augustoeliezer what version is that?

**Comment by augustoeliezer** [comment]
> @augustoeliezer what version is that?

3.1.1

**Comment by deirn** [comment]
[This modpack](https://www.curseforge.com/minecraft/modpacks/sky-fabrication-2-light)? It appears that it has crafting tweaks, can you try without it?

**Comment by deirn** [comment]
Hey @johannesmateboer can you try [this](https://github.com/badasintended/slotlink/suites/3874631669/artifacts/96424889) and see if your issue is fixed? I myself can't reproduce it anymore. Use the jar without `-dev` suffix.

**Comment by SOL3675** [comment]
> Same problem, when I crafting something and use REI to crafting some missing item, I lost one item.
> 
> Eg: red_bits:timer needs 4x minecraft:redstone torch nad 3x minecraft:stone
> 
> 1. I use REI to try craft and check I need more 1 redstone torch.
> 2. I use REI again to craft more one redstone torch
> 3. When I use REI to craft the timer still needing a redstone toch

I have the same issue.
I tested with only the slotlink dependencies and REI.

- architectury-2.5.28-fabric.jar
- cloth-config-5.0.38-fabric.jar
- fabric-api-0.40.1+1.17.jar
- fabric-langurage-kotlin-1.6.4+kotlin.1.5.30.jar
- RoughlyEnoughItems-6.0.279-alpha-fabric.jar
- slotlink-3.1.4.jar

Frabric Loader: 0.11.6
Java: Adopt Open JDK 16.0.2+7


How to reproduce

1. Make simple slotlink network and put 8 oak planks.
2. Set the chest recipe in the storage request crafting grid via REI.
3. You can see 1 planks missing.

**Comment by deirn** [comment]
@SOL3675 @augustoeliezer can you try [this file](https://github.com/badasintended/slotlink/suites/3916907117/artifacts/97893656) and see if 97c3475b277e332e0ccf3a91bcf608a8102a2add fixes it for you? Use the jar without `-dev` suffix.

**Comment by SOL3675** [comment]
@deirn This changed is fixed the problem for me.
I checked some recipes and it works fine.

**Comment by augustoeliezer** [comment]
I tried and the bug didn't happen. Publish this for a long test.
