### ISSUE TITLE
Items disappear with expanded storage and expanded storage inventory doesn't work

### ISSUE THREAD

**Issue by mtb-xt** [badasintended/slotlink#106]
**Setup**
- Minecraft: 1.17.1
- Fabric API: 0.40.1
- slotlink: 3.1.0
- related mod:  expanded storage 7.1.0

**Problem**
Hi, now link cables attach to expanded storage chests, but now sometimes items just disappear when I place them in (using wireless remote and shift clicking on items, if it matters). Also, items from expanded storage chests aren't visible in the wireless remote.

**Reproduction**
I had some preexisting expanded storage chests and I connected them to the network with link cables. I also upgraded some normal chests to expanded ones, and I think they worked, but I'm not 100% sure.

**Comment by deirn** [comment]
Do you play on server?

**Comment by mtb-xt** [comment]
> Do you play on server?

No, singleplayer.

**Comment by mtb-xt** [comment]
Again, I'm not sure if it matters, but when I look at normal chests, my WTHIT plugin shows their contents. When I look at expanded storage chest, it doesn't

**Comment by deirn** [comment]
Can I get your log?

> my WTHIT plugin shows their contents. When I look at expanded storage chest, it doesn't
I guess the plugin is megane? Now that you mentioned it, I'm not updated it to add support for Fabric Transfer API yet 😅

**Comment by mtb-xt** [comment]
> Can I get your log?
Sure, there's nothing in it, though... here -> https://paste.atlauncher.com/view/5e620fb5-0360-4782-a5a5-ca4542ad9480

> I guess the plugin is megane? Now that you mentioned it, I'm not updated it to add support for Fabric Transfer API yet sweat_smile

Yes, it's megane.

More details of the bug - so, I've tested with 'iron chest' placed into the network - it works. I've tested normal chest, connected to the network and then upgraded with 'wood to iron upgrade' - it works.

BUT!!!! I have a diamond double chest - and it's not working. Stuff from that chest is not visible in the network, but the chest is linked with a link cable. a golden double chest is also not working.
I even tried connecting them with 2 link cables, still nothing. 

Just in case - screenshot of chests layout
![2021-09-16_19 32 20](https://user-images.githubusercontent.com/11381295/133569782-f41d4bdb-0ac9-4b4e-85b8-57010937dae0.png)

**Comment by deirn** [comment]
Interesting, can you run `/data get block <x> <y> <z>` on the link cables that didn't work?
Also, can you send the `data/slotlink.dat` from the world folder?

**Comment by mtb-xt** [comment]
Here's the `slotlink.dat` file: 
[slotlink.dat.zip](https://github.com/badasintended/slotlink/files/7184443/slotlink.dat.zip)

**Comment by mtb-xt** [comment]
![2021-09-17_21 27 06](https://user-images.githubusercontent.com/11381295/133760613-05865e8b-a6c1-4934-a459-6f6904b94a12.png)
![2021-09-17_21 27 18](https://user-images.githubusercontent.com/11381295/133760628-3fb156e5-682a-4b08-8611-466982a9d36e.png)

**Comment by deirn** [comment]
Hmm, it looks like it doesn't actually connected to any network, if it is, it would have a `network` array value

**Comment by mtb-xt** [comment]
> Hmm, it looks like it doesn't actually connected to any network, if it is, it would have a `network` array value

I tried removing and placing them, but it's still like this. They're connected to the same cable as the other golden chest

**Comment by deirn** [comment]
Can you **backup your world**, replace the master block and see if it fixes it?

**Comment by mtb-xt** [comment]
> Can you **backup your world**, replace the master block and see if it fixes it?

So, I did this - I removed the master block, and placed it back - the link cables with the buggy chests showed the same thing, no network array. I clicked on my storage remote, it showed empty, even though the master block was connected at the exact same place.

I removed the master block again, placed it again in a different location but still at the same network, and after opening storage remote the game crashed. I'm reporting this just in case -> https://gist.github.com/mtb-xt/e384b17cfd2dd6a8ba54d462bbd372d7

If you want, I can export my whole world and it's instance and upload somewhere for you to debug. I'm using ATLauncher.

**Comment by mtb-xt** [comment]
Update - this did help, those two chests got connected, but I can consistently reproduce the crash - open the storage remote and start scrolling down. It always crashes roughly in the same place (same items)

**Comment by deirn** [comment]
The crash is different issue, looks easy to fix.

> If you want, I can export my whole world and it's instance and upload somewhere for you to debug.

Sure, you can send it to me @ `deirn#0100` on discord if you don't want it to be public.

**Comment by mtb-xt** [comment]
Apart from the crash, the original issue seems fixed. Do you still need the world?
Otherwise,I thank you very much for your help.
