### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by RozeFound** [badasintended/slotlink#107]
**Setup**
- Minecraft: 1.17.1
- Fabric API: 0.40.1
- slotlink: 3.1.0

**Problem**
In simple auto smelter coal is duplicating by stacks.
Crash report: There is nothing useful in the log.

**Reproduction**
Build simple auto smelter with 1 furnace, 2 exporters and 1 importer.

**Remarks**
Can send litematica template if is needed.

**Comment by deirn** [comment]
> Can send litematica template if is needed.
That would be cool since I don't know how to setup it 😅

**Comment by RozeFound** [comment]
Hah. Not a problem, I've firured out the problem is export and import cables which plug-ed to one block.
