### ISSUE TITLE
Render thread crash when moving items via REI

### ISSUE THREAD

**Issue by graeye** [badasintended/slotlink#11]
**Setup**

- Minecraft 1.16.1
- Fabric API - fabric-api-0.14.0+build.371-1.16.jar
- Fabric Language Kotlin - fabric-language-kotlin-1.3.71+build.1.jar
- slotlink - slotlink-0.3.1+minecraft-1.16.1.jar
- Spinnery - spinnery-3.0.50+fabric-1.16.x.jar (confirmed using included spinnery 3.0.51 from slotlink does not resolve)
- Pack: All of Fabric 3, modified.
- Crash log: https://pastebin.com/EV6PUw8r (Spinnery 3.0.50, clicking + to move items from REI)
- Crash log: https://pastebin.com/4qrMUspU (Spinnery 3.0.51 from slotlink jar, closing REI recipe screen)

**Problem**

- When clicking the + button to move items for crafting from a recipe via Roughly Enough Items, the game crashes and exits.

**Reproduction**

- I used an existing storage network upgraded from slotlink 0.2.7 and spinnery 3.0.48, in case that's relevant.
- Search for a recipe, I used iron bars from Minecraft. Select the recipe and click + to move items to craft that recipe.

**Remarks**

- Your release notes mention spinnery 3.0.51, but I do not see that version available on CurseForge. The current top comment says the .51 file was posted in error or the wrong version or something?
- I tried this with OptiFine and without; no change.
- I realize this is probably not your issue. Let me know if I should go check with Spinnery instead. :)

Edit: I suppose the crash log would help.

Thanks!

**Comment by deirn** [comment]
> upon a little bit of farther inspection, it appears closing the rei window is what crashes it? whenever i close out of the recipes window it crashes.

**Comment by deirn** [comment]
this is so weird, it's working on dev-env, it's working when its only slotlink and it deps, but it decided to crash on aof :/

**Comment by graeye** [comment]
> 
> 
> > upon a little bit of farther inspection, it appears closing the rei window is what crashes it? whenever i close out of the recipes window it crashes.

Same. Opening a recipe and then closing it crashes with another array index, triggered on a different event. This is with Spinnery .51 (not in /mods, but in slotlink jar).

https://pastebin.com/4qrMUspU

**Comment by deirn** [comment]
It seems that Inventory Sorter that caused the crash, disabled it and rei-crafting works fine.
Funny that the crash mentioned nothing about it.
I'll look it, but for now, disable Inventory Sorter :P

**Comment by deirn** [comment]
It also locks rei search bar for some reason

**Comment by deirn** [comment]
Added `"badasintended.slotlink.client.gui.screen.RequestScreen"` on `.minecraft/config/inventorysorter/blacklist.json5` and its working.
There's not much I can do with this, sorry.

**Comment by graeye** [comment]
> 
> 
> Added `"badasintended.slotlink.client.gui.screen.RequestScreen"` on `.minecraft/config/inventorysorter/blacklist.json5` and its working.
> There's not much I can do with this, sorry.

Are you serious right now? You just totally fixed this issue, how can you apologize for that? Confirmed it works perfectly for me now. Search bar behaving, can see and interact with recipes, can exit recipe or move items no drama. 

I'll send this information to the All of Fabric folks so they can add it to the default pack config, and maybe shoot a note to the inventory sorter people as well in case they can wrangle a code fix.

Either way, consider this issue resolved. Thanks muchly!

**Comment by deirn** [comment]
I'll leave this issue open incase someone else having the same issue

**Comment by TheVillageid10t** [comment]
Thank you for leaving this open I was looking for a fix for the past few hours lol

**Comment by deirn** [comment]
oh, i can pin this issue

**Comment by deirn** [comment]
there's remote now so add 
```
"badasintended.slotlink.client.gui.screen.RequestScreen"
"badasintended.slotlink.client.gui.screen.RemoteScreen"
``
to `.minecraft/config/inventorysorter/blacklist.json5`

**Comment by TheVillageid10t** [comment]
Ran into the issue again with accessing a Slotlink network and opening a recipe in REI or using the craft feature from REI.
Looking at the crash it says it was caused by Vazkii's Patchouli mod.

[crash-2020-08-06_15.34.52-client.txt](https://github.com/badasintended/slotlink/files/5038468/crash-2020-08-06_15.34.52-client.txt)
