### ISSUE TITLE
server crashed

### ISSUE THREAD

**Issue by MSandro** [badasintended/slotlink#110]
**Setup**
- Minecraft: 1.16.5
- Fabric API: 0.11.6
- slotlink: 2.4.2

**Problem**
Server Crash
https://pastebin.com/TUEkwp4N
https://gist.github.com/deirn/304a8fbb37fdef715c8b394378bfe664

**Reproduction**
Not sure exactly, jus me and my friend interacted with the slotlink network.

**Comment by deirn** [comment]
Did you link other mod container? If so what it is?

**Comment by MSandro** [comment]
We have just some Storage Cabinets and Chests from Expanded Storage connected with the Slotlink System

**Comment by deirn** [comment]
Can you try disconnecting the storage cabinets and see if it crashes? Might be incompatibility with them. I honestly don't recommend using slotlink with more unique containers, expanded storage should be fine though

**Comment by MSandro** [comment]
I had been using Storage Cabinets with Slotlink for a long time, always without any problems. This is the first time since the server crashed because of slot link. But the crash report contains the following lines:
`at badasintended.slotlink.screen.RequestScreenHandler.method_7623(RequestScreenHandler.java:508)`
It has something to do with a GUI, doesn't it? Perhaps there was code that was actually not supposed to run on the server?

**Comment by deirn** [comment]
Something to do with container changing size while the request screen open

**Comment by MSandro** [comment]
Oh, okay. My friend said he would like to upgrade the cabinets. That was probably what caused the crash.
