### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by MSandro** [badasintended/slotlink#115]
**Setup**
- Minecraft: 1.17.1
- Fabric API: 0.12.11
- slotlink: 3.1.7
- related mod: n/a

**Problem**
the server crashed
Crash report: https://gist.github.com/MSandro/92f35e16a46565d0db6fae03ad9173f7#file-crash-2021-12-13_07-17-36-server-txt

**Reproduction**
what I did: just stacked up coal to coal blocks, lapis, redstone, and so on -> 

**Remarks**
Modpack Sky FABRICation v0.9.2
might be a compatibillity issue with Recipe Cache Mod?

**Comment by deirn** [comment]
Can you try this file? The jar is inside the zip.
[slotlink-local.zip](https://github.com/badasintended/slotlink/files/7713155/slotlink-local.zip)

**Comment by MSandro** [comment]
thanks, it solves the issue.

**Comment by deirn** [comment]
Closed in 1b511c9
