### ISSUE TITLE
Dupe with Slotlink Crafting

### ISSUE THREAD

**Issue by AtPMonster** [badasintended/slotlink#116]
**Setup**
- Minecraft: 1.17.1
- Fabric API: 0.12.8
- slotlink: 3.1.7
- related mod: Playing on a Modpack called "Sky FABRICation 2" Version 0.9.2

**Problem**
_State your problem here._
Crash report: _if any, upload it on paste website and copy the link._

Crash Report---> https://ucarecdn.com/5518d13e-824b-4d1f-a057-ce271b7c7328/

Duping with Slotlink crafting Terminal.
[crash-2021-12-13_08.12.44-server.txt](https://github.com/badasintended/slotlink/files/7704516/crash-2021-12-13_08.12.44-server.txt)

**Reproduction**
_Explain how you set up the storage network. Maybe attach some screenshots._

Actually pretty simple. I pick a stackable block like redstone blocks, try to convert them into dust and just spam the convert. I dont lose any redstone blocks but get tons of redstone dust since my Inventory is full and the all new redstone dust gets send into the system automatic.

**Remarks**
_Additional info lies here_

**Comment by MSandro** [comment]
I can confirm this issue. if the inventory is full and you continue crasfting, items will be put in a lotlink container, but ingredients will not be consumed. I've trested this in single player with a small slotlink network with just a vanilla chest connected!

**Comment by 0gp** [comment]
I can confirm this issue too, And it is NOT a compatibillity bug! I've tested this with a new 1.17.1 instance with just FABRIC API 0.44.0, Slotlink 3.1.7 and fabric language kotlin 1.7.0+kotlin.1.6.0 installed.
