### ISSUE TITLE
Blacklist does not work on link cable 

### ISSUE THREAD

**Issue by Adirelle** [badasintended/slotlink#117]
**Setup**
- Minecraft: 1.18.1
- Fabric API: 0.44.0+1.18
- slotlink: compiled from 1.18 branch
- related mod: none

**Problem**
It seems the blacklist settings on link cable does not prevent listed items to be added to the linked chest.

**Reproduction**
* Create a slotlink network with only one chest for storage.
* Set the link cable mode to "blacklist".
* Add cobblestone to the filter of the link cable.
* Try to store a cobblestone through the storage request.
What is expected: the request storage refuses to take the item.
What actually happens: the cobblestone is stored in the chest.

**Comment by Adirelle** [comment]
Digging a bit in the sources, I am not sure I understand those lines correctly:https://github.com/badasintended/slotlink/blob/41660838735ada7947c66316b2e3661ea3a5e57b/src/main/kotlin/badasintended/slotlink/storage/FilteredItemStorage.kt#L37-L38

It seems to me that the tests are in the opposite of what the method names means (i.e. that canInsert would return false when insertion is possible and conversely).

**Comment by deirn** [comment]
The flag indicates when the filter is applied. If it's `false` then the filter wouldn't be called and it returns always true.

**Comment by Adirelle** [comment]
Ah, it makes more sense. I am not sure why it the filter does not work then. Maybe another mod is involved though.

**Comment by Adirelle** [comment]
Ok, I was mistaken about what happens. When I set a whitelist on a link cable, all the items in the linked chest are visible in the request table. However, I can only grab those that matches the whitelist *and* it can store any item *into* the chest. It seems to work like an extract whitelist.

This does not seems affected by other chest/inventory-related mods (inventory sorter, mouse tweaks, easy chests) since it also happens when I disable them. I have tried to remove and setup again the link cables as well as the network master to no avail.

**Comment by deirn** [comment]
Hmm, it's working fine for me, I can only put items that match the filter to the chest. How's your setup?

**Comment by Adirelle** [comment]
4 double chests, with two of them having priority 2 and the same whitelist (here cobblestone and granite), a furnace connected with 2 export cables and one import cable.

![2021-12-16_08 48 39](https://user-images.githubusercontent.com/24633/146329827-148fa177-6b4f-4471-807f-21ee62f4ba97.png)

I thought it was an issue with the link cables, but I just reproduced it in a creative world with only linkslot. Apparently, the import and export cables have something to do with it.
