### ISSUE TITLE
Multiple links to single chest disables entire system [0.3.2 - 0.3.3]

### ISSUE THREAD

**Issue by graeye** [badasintended/slotlink#12]
**Setup**

- Minecraft 1.16.1
- Fabric API - fabric-api-0.14.0+build.371-1.16.jar and fabric-api-0.14.1+build.372-1.16.jar
- Fabric Language Kotlin - fabric-language-kotlin-1.3.71+build.1.jar
- slotlink - slotlink-0.3.2+minecraft-1.16.1.jar and slotlink-0.3.3-cursed+minecraft-1.16.1.jar
- Pack: All of Fabric 3, modified.

**Problem**

- If multiple storage link cables connect to a single chest, the Network Master correctly reports still but the Storage Request block no longer responds when clicking it.

**Reproduction**

- Make an L with storage link cables and place a chest on the inside so that 2 links connect to it. See picture.
- https://imgur.com/a/76LuNXF

**Remarks**

- No difference between slotlink 0.3.2 and 0.3.3.
- No change between Fabric API 0.14.0 and 0.14.1.
- Same behavior with vanilla Minecraft chest and modded chests.

**Comment by deirn** [comment]
not a critical bug but i think i know how to fix this
