### ISSUE TITLE
Crash when I place the master block down.

### ISSUE THREAD

**Issue by Fruitsalad96** [badasintended/slotlink#129]
**Setup**
- Minecraft: 1.18.1
- Fabric API: 0.13.1-1.18.1
- slotlink: 4.2.1

**Problem**
Whenever I place the master block I crash. 
Crash report: https://pastebin.com/3ykuGnvv

**Reproduction**
I place the block down. With or without anything else it crashes regardless.

**Comment by deirn** [comment]
Can you try deleting `.minecraft/config/slotlink.json` and see if it fixes it?

**Comment by Fruitsalad96** [comment]
I completely deleted my minecraft and redownloaded it and it works now. I have no clue what was making it buggy in the first place.

**Comment by deirn** [comment]
The config was probably getting corrupted, though I'm not really sure.
