### ISSUE TITLE
Double chests are read as single chests [0.3.3]

### ISSUE THREAD

**Issue by graeye** [badasintended/slotlink#13]
**Setup**

- Minecraft 1.16.1
- Fabric API - fabric-api-0.14.1+build.372-1.16.jar
- Fabric Language Kotlin - fabric-language-kotlin-1.3.71+build.1.jar
- slotlink - slotlink-0.3.3-cursed+minecraft-1.16.1.jar
- (optional) Expanded Storage - expandedstorage-5.3.15+1.16.jar
- Pack: All of Fabric 3, modified.

**Problem**

- Double chests are read as a single chest. This is true of both Vanilla and [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric) chests.

**Reproduction**

- Create a double chest by placing two horizontally. Attach to network and look at Network Master capacity. Remove the chest not directly connected to slotlink and view capacity again. It won't reflect the 2nd chest being added or removed.
- Alternately you can create a double chest, connect it to slotlink, and then fill the system completely. If you check the chest it will be exactly half full.

**Remarks**
- I initially thought this was a mod compatibility issue with Expanded Storage, but get the same results with a vanilla double chest. If this is by design, just let me know. Not a huge issue either way, just didn't know if it was intentional.

Thanks again!

**Comment by deirn** [comment]
yeah sorry, i can't find an optimal way to checking multiblock inventory...

**Comment by graeye** [comment]
No problem. Chalk it up to "working as intended."
