### ISSUE TITLE
Game crashes as soon as i place down a network master or if im even in a world with anything from slotlink

### ISSUE THREAD

**Issue by Karim246** [badasintended/slotlink#131]
**Setup**
- Minecraft: 1.18.1
- Fabric API: 0.46.4+1.18
- slotlink: 4.2.1
- related mod: N/A

**Problem**
Game crashes as soon as i place down a network master or if im even in a world with anything from slotlink
Crash report: https://github.com/Karim246/crash/blob/main/crash

**Reproduction**
Normally, it was working fine until today when i booted up mc and it would crash if i went in a world with anything from slotlink. But yeah just some link cables all connecting to the storage request.

**Remarks**
_Additional info lies here_

**Comment by deirn** [comment]
Can you tey deleting `.minecraft/config/slotlink.json` and try again? 

Strange that people has this issue recently as i didn't touch config code since 6 months ago (#129) 🤔

**Comment by Karim246** [comment]
lol how exactly can i do that sorry new to this

**Comment by Karim246** [comment]
oh wait nvm im being stupid i know how to do that

**Comment by Karim246** [comment]
Thanks alot man this worked
