### ISSUE TITLE
You can't drag-shift-click multiple items from storage

### ISSUE THREAD

**Issue by KTibow** [badasintended/slotlink#132]
**Setup**
- Minecraft: 1.18.1
- Fabric API: 0.46.4+1.18.1
- slotlink: 4.2.1
- related mod: N/A

**Problem**
In vanilla, if you hold shift, click, and move your mouse across multiple slots, you move the items from one container into another. In the slotlink storage GUI, you only move the first one.
Crash report: N/A

**Reproduction**
Not relevant, but anyway:
https://user-images.githubusercontent.com/10727862/154188151-da12a3cf-470c-4724-ab3b-a6788b48a2fa.mp4

**Remarks**
N/A

**Comment by deirn** [comment]
Are you sure that's vanilla feature? Can you send me your `latest.log` / mod list?

**Comment by KTibow** [comment]
Wait I totally didn't realize that feature was provided by a mod. Let me test which one provides that functionality.

**Comment by KTibow** [comment]
Apparently it's provided by Inventory Profiles Next. It would be nice if it was compatible with that mod, but given that the storage container doesn't have empty slots, you would need to do something weird.
