### ISSUE TITLE
Shift-click gives full stack output without required ingredients [0.3.3]

### ISSUE THREAD

**Issue by graeye** [badasintended/slotlink#14]
**Setup**

- Minecraft 1.16.1
- Fabric API - fabric-api-0.14.1+build.372-1.16.jar
- Fabric Language Kotlin - fabric-language-kotlin-1.3.71+build.1.jar
- slotlink - slotlink-0.3.3-cursed+minecraft-1.16.1.jar
- Pack: All of Fabric 3, modified.

**Problem**

- Shift-clicking the recipe output for any recipe crafts 64 of that recipe, even without required ingredients being in storage.

**Reproduction**

- Network Master with 1 cable and 1 chest. Storage Request attached to Master. Don't need any items in storage.
- Place 9 iron ingots in craft grid of Storage Request. Shift-click the Iron Block. You will lose the iron ingots (as expected) but gain 64 iron blocks instead of just 1. This worked on every recipe I tried; diamonds to diamond blocks, iron ingots to iron bars, vanilla chests to iron chests (modded), gold ingots to nuggets, etc.
- See pictures for a few examples. https://imgur.com/a/L274t0r

**Remarks**

- Sorry to keep making work for you. Love the mod!

**Comment by deirn** [comment]
good thing i name this org badasintended :P 
I'll work on it after I got home

**Comment by deirn** [comment]
bruh, it's exactly one line to fix this

**Comment by deirn** [comment]
ohno got another issue, need to redo the logic

**Comment by deirn** [comment]
should be fixed on 0.3.4
