### ISSUE TITLE
Remote Storage Keybind.

### ISSUE THREAD

**Issue by PlayfulPiano** [badasintended/slotlink#148]
Simple suggestion here, but basically if you have a Remote Storage item of any type within your inventory, you can access the storage UI easily through a keybind.

**Comment by pianoboy8** [comment]
Actually a small addon to this that I thought of: include a trinket mod slot for the storage remote. This way the item itself doesn't take an item slot and instead is equippable.
(trinket is fabric's baubles variant here: https://www.curseforge.com/minecraft/mc-mods/trinkets)
