### ISSUE TITLE
Rare crash from Storage Request screen when leaving it. [0.3.5]

### ISSUE THREAD

**Issue by graeye** [badasintended/slotlink#16]
**Setup**

- Minecraft 1.16.1
- Fabric API: fabric-api-0.14.1+build.372-1.16.jar
- Fabric Language Kotlin: fabric-language-kotlin-1.3.71+build.1.jar
- slotlink: slotlink-0.3.5+minecraft-1.16.1.jar
- inmis: inmis-1.1.1-1.16.1.jar
- REI: RoughlyEnoughItems-4.9.5.jar
- Pack: All of Fabric 3, modified.
- Crash report: https://pastebin.com/c2VjdDt2
- Crash report 2: https://pastebin.com/t3PDesqe

**Problem**

- Crash in Storage Request screen while attempting to close it.

**Reproduction**

- I think this is that very rare crash I was telling you about. I cannot force a reproduction, it's just something that happens occasionally. I had opened the Storage Request screen and either clicked outside of it or hit E or escape and got the "Saving World..." message.
- The current setup shows spinnery 3.0.48, Astromine backed down their version, and it is not present in /mods.
- REPRO: With full inventory, and items on the ground that will get picked up if you empty an inventory slot, open an inmis (I need more storage) backpack. On that screen, there should be no REI display. Click an item in inventory to pick it up, and let an item on the ground fill the slot. Click on the empty right side where REI would normally be. REI should then appear and open a recipe automatically (where you clicked the invisible REI I'm guessing). Closing that recipe causes the crash.

**Remarks**

- Since I can't force a repro and this happens so infrequently, I wouldn't stress too much. Just thought I'd post in case something immediately jumps out at you.
- [Jul 15 2020] Added inmis and REI to setup. Updated repro steps.
- [Jul 15 2020] Added 2nd crash report.

**Comment by deirn** [comment]
all right, thank you. this may take some time to debug

**Comment by graeye** [comment]
Finally got a repro. This isn't a slotlink problem, but either spinnery or REI or the combination of the two with inmis.

I've updated the initial post with the repro steps, but what happens is with full inventory open an inmis bag. There will be no REI displayed. But if you click to the right side where REI would normally be, REI appears and opens a recipe. Exiting that screen crashes every time.

**Comment by deirn** [comment]
maybe that's a different crash? i mean, there's my code path in the prev report...

and yeah, the REI click area is there but the items don't render, this is fixed with a simple call to super.
https://linediff.com/?id=5f0fa270687f4b4c258b4567
the crash though, maybe another inventory sorter related one?
try adding `draylar.inmis.ui.BackpackContainerScreen` to backlist

**Comment by graeye** [comment]
Looking at the crash log, you're right it's in REI, so while this is what I was thinking of, it's not the same crash. Hrmph.

REI crash report: https://pastebin.com/fFtuavKk

**Comment by deirn** [comment]
looks like #11, really.
maybe inventory sorter doesn't support all spinnery guis?
also the item rendering is spinnery's fault

**Comment by graeye** [comment]
Yeah, I think it's related. The only reason it's special is that REI isn't even visible until you click where it isn't... and then RIP. No way out.

**Comment by deirn** [comment]
that's spinery fault, BaseContainerScreen#render doesn't call super :P
left is vini's 3.0.48, right is slotlink's 
https://linediff.com/?id=5f0fa270687f4b4c258b4567

**Comment by graeye** [comment]
I'm sure it's fixed in 3.0.54. Too bad everything else is broken. >.<

**Comment by graeye** [comment]
Hit it again on my test world. Nothing crazy, single chest system with only a few stacks of items in it. Grabbed a 64 stack out of ~190 item stack and hit escape to exit the Storage Request and crashed out.

This is the screen that's already blacklisted from inventorysorter.

Report: https://pastebin.com/t3PDesqe

**Comment by deirn** [comment]
this took way too long, sorry for that
looking at it, it doesn't make any problem beside of crashing so try-catching is the way to go
