### ISSUE TITLE
crash when moving items from request screen to inventory 

### ISSUE THREAD

**Issue by peanutinky** [badasintended/slotlink#17]
not sure but it looks like spinnery causing this crash. ticking entity
here is the crash report
https://pastebin.com/dggExs6j

**Comment by deirn** [comment]
alright, i'll investigate it later

**Comment by deirn** [comment]
@peanutinky can you tell me what inventory is connected to the network?

**Comment by deirn** [comment]
closing since now i'm using upstream spinnery now
