### ISSUE TITLE
Crash when closing GUI

### ISSUE THREAD

**Issue by TheVillageid10t** [badasintended/slotlink#18]
Singleplayer

Survival

Steps:
1-access network
2-set network sorting to "count"
3-throw in stacks of random items from ground (probably about 3 chests worth of items)
4-scroll through and make sure all items made it in
5-press "E" to close network GUI (also reloaded again and tried by hitting escape instead to see if it would do anything different... same thing happens)
6-crash

Tried it without sorting by "count"
everything works fine

https://paste.ee/p/VPiS0

P.S. Sorry if this was already reported and if you already know about this.

**Comment by deirn** [comment]
this is probably same as #16 that i have trouble debugging, very appreciated the detail thanks
