### ISSUE TITLE
Crash when exporting items to a single slot inventory without filter set

### ISSUE THREAD

**Issue by kibmcz** [badasintended/slotlink#21]
**Setup**
- Minecraft: 1.16.1
- Fabric API: 0.90+BUild.204
- slotlink: 1.0.1
- Spinnery: {bundled version}
- related mod: VERSION

**Problem**
If a export cable is connected to a storage inventory that only takes one stack and isn't configured with a filter it will attempt to pipe everything to that target inventory resulting in crash.
Crash report: https://pastebin.com/3SLaW1UP

**Reproduction**
Place stockpile item barrel configured to a particular item then connect to storage network with a export cable without setting up filter.

**Remarks**
Would be more ideal for it to just send the item the single slot inventory can accept without attempting to send everything to it.

**Comment by deirn** [comment]
Forgot to check whether the stack is valid. Should be fixed in 1.0.2.
Also fun fact, for whatever reason, there are actually two slots in the drawer, and the first slot won't accept any item.
