### ISSUE TITLE
GUI of storage request block is a bit too large when used with roughly enough items

### ISSUE THREAD

**Issue by Luro02** [badasintended/slotlink#23]
**Setup**
- Minecraft: 1.16.1
- Fabric API: idk
- slotlink: v1.0.2+minecraft-1.16.1
- Spinnery: v3.1.13
- related mod: All of Fabric 3 - 1.5.1

**Problem**
![Screenshot_20200805_132120](https://user-images.githubusercontent.com/24826124/89407169-98c10a00-d71e-11ea-9fa9-9f56366dc673.png)

The GUI for `Storage Request` is overlapping with the roughly enough items search.

**Reproduction**

1. Install `All of Fabric 3`
2. ESC > Options > Video Settings > GUI Scale: 3
2. Build a storage network
3. Right click on Storage Request Block

**Comment by deirn** [comment]
Not actually a problem with slotlink since it'll affect any gui. The nicest approach is probably making the size configurable but I don't really want to make a config only for that, sorry.
I believe you can set the rei search bar to the right side like how jei defaults to.
