### ISSUE TITLE
java.lang.NullPointerException: mouseReleased event handler

### ISSUE THREAD

**Issue by Luro02** [badasintended/slotlink#26]
**Setup**
- Minecraft: 1.16.1
- Fabric API: idk
- slotlink: v1.0.2+minecraft-1.16.1
- Spinnery: v3.1.13
- related mod: All of Fabric 3 - 1.5.1

**Problem**
Pressing an extra button on my mouse, while I have the gui for slotlink open (crafting request) crashes minecraft.

Crash report: https://ghostbin.co/paste/rkp67

**Comment by deirn** [comment]
you should report this to spinnery, as I don't make any check on onMouseReleased

**Comment by Luro02** [comment]
I also reported this to astromine (same issue) and they said it would be fixed with the next update https://github.com/Chainmail-Studios/Astromine/issues/198

**Comment by deirn** [comment]
Astromine doesn't use spinnery anymore, so i reopened this issue.

**Comment by deirn** [comment]
well, since i forked spinnery and using that fork I'm gonna close this
