### ISSUE TITLE
Mouse click Event Handler Crash when using REI in conjunction with Slotlink

### ISSUE THREAD

**Issue by TheVillageid10t** [badasintended/slotlink#27]
**Setup**
- Minecraft: 1.16.1
- Fabric API: 0.16.2+build.385
- slotlink: 1.0.3
- Spinnery: 3.0.59
- Roughly Enough Items: 4.10.5

**Problem**
_Mouse click Event Handler Crash when using REI in conjunction with Slotlink_

Crash report: 

[crash-2020-08-06_15.34.52-client.txt](https://github.com/badasintended/slotlink/files/5038581/crash-2020-08-06_15.34.52-client.txt)

**Reproduction**
_- Create Slotlink Network
- access network
- open recipe in REI
- Exit network/craft item from jei through Slotlink Network crafting table
- Crash_

![ezgif com-optimize](https://user-images.githubusercontent.com/67838934/89593963-7bb33680-d805-11ea-95e0-987569372378.gif)

**Comment by deirn** [comment]
it's still the same as #11, really. maybe the config changed? :thinking:https://github.com/TeamAOF/AOF-Strawberry/issues/26 for the exact file
