### ISSUE TITLE
Storage link cables can't be /setblock'd or /fill-ed, generating null pointer exceptions

### ISSUE THREAD

**Issue by James103** [badasintended/slotlink#28]
**Setup**
- Minecraft: 1.16.1
- Fabric API: 0.16.0+build.384-1.16.1
- slotlink: 0.3.6+minecraft-1.16.1
- Spinnery: 3.1.13
- Modpack: All of Fabric 3 1.4.2

**Problem**
By running the following command: `/setblock ~ ~ ~ slotlink:link_cable`, you get an error: "An unexpected error occurred trying to run this command". Hovering over the above text says "kotlin.KotlinNullPointerException". No additional logs or crash report is created.

`/setblock ~ ~ ~ slotlink:cable`, `/setblock ~ ~ ~ slotlink:request`, and `/setblock ~ ~ ~ slotlink:master` all work, and so does placing the storage link cable manually or cloning it using the `/clone` command.

**Expected result**
Running the command `/setblock ~ ~ ~ slotlink:link_cable` should actually place a link cable from slotlink.

**Comment by deirn** [comment]
lol i'll look to it, thanks

**Comment by deirn** [comment]
bruh thanks to https://github.com/ByMartrixx/wdmcf
