### ISSUE TITLE
Server crash when putting items in storage request

### ISSUE THREAD

**Issue by ryancflowers** [badasintended/slotlink#3]
Seems to trigger after shift clicking a few stacks of items into it. Very reproducible.

https://pastebin.com/JwE2BHgd

**Comment by deirn** [comment]
working on the fix
it seems i need to override the mouse click event which is pretty annoying lol

**Comment by deirn** [comment]
nevermind that's a different issue, just need to remove one line

**Comment by deirn** [comment]
should be fixed with 0.2.2
