### ISSUE TITLE
Does not respect Automated Crafting Table's slot limitations

### ISSUE THREAD

**Issue by supersaiyansubtlety** [badasintended/slotlink#31]
**Setup**
- Minecraft: 1.16.1
- fabricloader: 0.9.0+build.204
- fabric-api: 0.17.0+build.386-1.16.1
- fabric-language-kotlin: 1.3.72+build.1
- automated-crafting: 1.3.0+1.16.1
- slotlink: 1.1.1+minecraft-1.16.1
- modmenu: 1.14.5+build.30

**Problem**
https://gitlab.com/supersaiyansubtlety/automated_crafting/-/issues/3

**Reproduction**
Point export cable into Automated Crafting Table. 

**Remarks**
I'm the dev of Automated Crafting Table. 

I looked in [ExportCableBlockEntity](https://github.com/badasintended/slotlink/blob/1.16/src/main/kotlin/badasintended/slotlink/block/entity/ExportCableBlockEntity.kt) and didn't see anything obvious (though I'm not familiar with kotlin). 
I couldn't get slotlink into my dev environment using CurseMaven, so if you know how I could do that (I think a `-sources.jar` will run in dev environments?) I'd be grateful so I could look into this more. 

If it helps, [here](https://gitlab.com/supersaiyansubtlety/automated_crafting/-/blob/master/src/main/java/net/sssubtlety/automated_crafting/blockEntity/SimpleAutoCrafterBlockEntity.java#L40) is the check that prevents hoppers from inserting more than 1 item into a slot, and [here](https://gitlab.com/supersaiyansubtlety/automated_crafting/-/blob/master/src/main/java/net/sssubtlety/automated_crafting/blockEntity/AbstractAutoCrafterBlockEntity.java#L175) is the method it should be reached from.

**Comment by deirn** [comment]
Welcome to my mess :P
i guess i'll just use hopper's method to handle the transfer :thinking: 

and cursemaven doesn't seem to pull its dependencies, so i recommend using jitpack

**Comment by deirn** [comment]
```gradle
repositories {
    maven {
        name = "Spinnery"
        url  "https://dl.bintray.com/spinnery/Spinnery"
    }
    maven { url 'https://jitpack.io' }
}

dependencies {
    modRuntime 'com.github.badasintended:slotlink:<version>'
}
```

**Comment by deirn** [comment]
i'll also look to it, but i have something else to do atm

**Comment by supersaiyansubtlety** [comment]
Ok, and thanks, I'll try jitpack.

**Comment by supersaiyansubtlety** [comment]
Ok, found the issue and it's (mostly) on my end. Cables appear to insert entire stacks at a time, and I was expecting items to be inserted 1 at a time. 

However if I just add a check so that I deny insertion for any stack with count > 1, slotlink won't get to insert at all. Maybe you could, after trying to insert a full stack fails, try to insert 1 item from the stack? Or it might have better performance (but behave a bit strangely) if you tried inserting 1 first and if that succeeds try inserting the rest?

**Comment by deirn** [comment]
it actually loops and moves 1 item at a time though, it always checking `Inventory.isValid()` and break if false
https://github.com/badasintended/slotlink/blob/488aee6ec823f991ceb28d308f6225ae2a158cb9/src/main/kotlin/badasintended/slotlink/common/util/Utils.kt#L122-L139

**Comment by supersaiyansubtlety** [comment]
Oh, wtf Mojang, why  is there `isValid` and `canInsert`?

Looks like I also need to override `isValid` for my inventory. 

The check Automated Crafting is dependent on is `canInsert`, which is being called properly (once per stack it looks like) in the ExportCableBlockEntity, hence it seeming like it inserted all at once. 

Closing issue as this isn't on your end. 

I'm still not sure what the best way to make it compatible with other mods is though. I feel like I should still have the check `stack.getCount() == 1` for both `isValid` and `canInsert`. This would still mean other mods would have to call `canInsert` with only 1 item stacks. Any advice?

**Comment by deirn** [comment]
`canInsert` and `canExtract` is only for `SidedInventory`, I'll probably do another check to ensure compatibility

**Comment by supersaiyansubtlety** [comment]
For some reason even when I override it, my `isValid` method isn't reached in `mergeStack`, which is instead going to the default method in `Inventory`. 

I do reach my `isValid` method if I make the call `<reference_to_my_custom_inventory_class_member>.isValid(slot, stack)`. 

Any idea why that might be?

**Comment by deirn** [comment]
now that's cursed

**Comment by Adirelle** [comment]
Could this be related to the way kotlin extensions are handled ? Something about https://kotlinlang.org/docs/reference/extensions.html#extensions-are-resolved-statically (I've not checked the code yet.)

**Comment by deirn** [comment]
added `canInsert` check on `mergeStack`, should be working as intended on 1.1.3

**Comment by Adirelle** [comment]
With 1.1.3 it inserts items properly in the autocrafting table.

But 1.1.3 has also introduced a duplication bug, see https://github.com/badasintended/slotlink/issues/32

**Comment by supersaiyansubtlety** [comment]
It looks like 1.1.3 will stop being able to insert into Auto Crafters when I update it so that it doesn't allow the insertion of stacks with `stack.getCount != 1`, based on [this `isValid` check](https://github.com/badasintended/slotlink/blob/1.16/src/main/kotlin/badasintended/slotlink/block/entity/ExportCableBlockEntity.kt#L24) taking passing the whole stack. 

Since you're checking both isValid and canInsert in Inventory.mergeStack, I think you can just call mergeStack without any check in `ExportCableBlockEntity`.

I'm also not sure the for loop in `Inventory.mergeStack` is correct (though it might just be my inexperience with Kotlin). 
What I was expecting to see instead of
```kotlin
for (i in target.count until target.maxCount) {
    if (!isValid(slot, source)) return
    if (this is SidedInventory) if (!canInsert(slot, source, side)) return
    ...
}
```
something like (java b/c it's what I know)
```java
ItemStack singlePeekStack = new ItemStack(source.getItem());
while (!source.isEmpty() && isValid(slot, sliglePeekStack) && (!(this instanceof SidedInventory) || canInsert(slot, singlePeekStack))) {
    if (getStack(slot).isEmpty())
        setStack(slot, source.split(1));
    else if (!StackUtilities.equalItemAndTag(source, target)) {
        target.increment(1);
        source.decrement(1);
    }
}
```
or, to maximize optimality 🤓 (by avoiding redundant instanceof checks)
```java
ItemStack singlePeekStack = new ItemStack(source.getItem());
BiPredicate<Integer, ItemStack> sidedCheck = (this instanceof SidedInventory ? (slot, stack) -> canInsert(slot, singlePeekStack) : (slot, stack) -> true;
while (!source.isEmpty() && isValid(slot, sliglePeekStack) &&  sidedCheck.check(slot, singlePeekStack)) {
    ...
}
```
There are probably tons of typos in there because for some reason I thought it would be a good idea to write code in the github comment interface...

**Comment by deirn** [comment]
because of the nature of kotlin, I cant combine `instanceof` check with `(SidedInventory) this`.
and `target` is not changed when you `setStack()`, cool right? :P

**Comment by supersaiyansubtlety** [comment]
Do you still need to store `target` at all?
As for the `instanceof` and `(SidedInventory) this`, couldn't you just expand it into nested `if`s? Clunky, but can't imagine it not working.

**Comment by deirn** [comment]
> Do you still need to store `target` at all?

still need to check `count < maxCount` otherwise it'll merge into 65

> couldn't you just expand it into nested `if`s?

I already done it?
https://github.com/badasintended/slotlink/blob/1b8f49a4b5c3c9493b21dd6d1009f402b2fb1846/src/main/kotlin/badasintended/slotlink/common/util/Utils.kt#L129

**Comment by Adirelle** [comment]
As far as I can tell, 1.1.4 fixes the issue.

**Comment by supersaiyansubtlety** [comment]
mergeStacks looks like it will work with Automated Crafting in 1.1.4, but [this check](https://github.com/badasintended/slotlink/blob/1.16/src/main/kotlin/badasintended/slotlink/block/entity/ExportCableBlockEntity.kt#L24) in `ExportCableBlockEntity` will still prevent insertion into the (not-yet-released) updated version of automated crafting, since it checks if the whole stack can insert. 

I think you can omit that check in `ExportCableBlockEntity` as it's made again in `mergeStack` anyways, except in `mergeStack` it checks insertion of a single item.

**Comment by deirn** [comment]
no that's checking if the filter accepts that stack
https://github.com/badasintended/slotlink/blob/1b8f49a4b5c3c9493b21dd6d1009f402b2fb1846/src/main/kotlin/badasintended/slotlink/block/entity/TransferCableBlockEntity.kt#L40-L49

**Comment by deirn** [comment]
the method name may confuse you, sorry for that

**Comment by supersaiyansubtlety** [comment]
Ohhh, my bad. Cool, I should be able to release my update tomorrow.
