### ISSUE TITLE
The Export Cable duplicates items

### ISSUE THREAD

**Issue by Adirelle** [badasintended/slotlink#32]
**Setup**
- Minecraft: 1.16.1
- Fabric API: 0.17.0+build.386-1.16.1
- slotlink: 1.1.3
- Spinnery: shipped with slotlink.

**Problem**
Export Cable does not remove the exported items.

**Reproduction**
1. Build a network with two chests, a network master, a link cable pointing to the first chest and an export cable pointing to the second chest.
2. Put a stack of any item in the first chest.
3. Check the content of the second chest: it is slowly filling with the items.
4. Check the content of the first chest: the stack of items is untouched.

**Remarks**
Probably related to https://github.com/badasintended/slotlink/commit/5d8705a546e377ace6d7ab63a9bd552f56d9a589#diff-3f88592151864276afd0f1562c659a21R23.

**Comment by deirn** [comment]
ah sheet, i know exactly why.
i added `.copy()` so the transfered item is new instance. 🤦‍♂️
will fix tommorow morning
