### ISSUE TITLE
Left click gesture works only sometimes

### ISSUE THREAD

**Issue by Luro02** [badasintended/slotlink#34]
The left click gesture (to distribute items evenly) works for me only sometimes:

https://youtu.be/SkeX58yDICg

**Comment by deirn** [comment]
should be a bug :P

**Comment by Luro02** [comment]
oh yeah

**Comment by deirn** [comment]
is it still occurring on 1.1.5? because it works fine on my end now

**Comment by Luro02** [comment]
No it does not seem to occur with the new version
