### ISSUE TITLE
Crash when i link more than 11 storages

### ISSUE THREAD

**Issue by PadreMathias** [badasintended/slotlink#36]
**Setup**
- Minecraft: 1.16.1
- Fabric API: fabric-api-0.17.0+build.386-1.16.1
- slotlink: slotlink-1.1.5+minecraft-1.16.1
- Spinnery: spinnery-3.1.13+fabric-1.16.x
- related mod: VERSION

**Problem**
When i place a link cable in a chest my game crash and i can't open the world again without my game crash.
Crash report: _if any, upload it on paste website and copy the link._

**Reproduction**
I don't have screenshot, i was linking a chest into my system then my game crashes it.

**Crash log**
https://pastebin.com/ZF6GmL7K
[crash-2020-08-19_11.29.27-server.txt](https://github.com/badasintended/slotlink/files/5098567/crash-2020-08-19_11.29.27-server.txt)

**Comment by deirn** [comment]
this actually shouldn't happen on regular inventories, but something decided to return `null` instead of empty stack

**Comment by deirn** [comment]
should be fixed in 1.1.6
