### ISSUE TITLE
Shift clicking

### ISSUE THREAD

**Issue by uhAiko** [badasintended/slotlink#38]
I'd say for the Storage Request block, when shift clicking items in the crafting menu, make them go into the storage system rather than back into your inventory. Convenience is key :P

**Comment by Adirelle** [comment]
By the way, I had some weird display behavior with the crafting grid (be it in Storage Request or with the Remote) when crafting several items in one run, like "ghost items" in the grid, preventing to use a new recipe until I clear the grid, or the mouse pointer showing the result of the previous recipe but actually holding the right items. I will try to reproduce them and do more detailed reports when I will have some time.

**Comment by deirn** [comment]
ah, i need to explicitly clear the result slot. missed that, thanks

**Comment by deirn** [comment]
no. is for the original suggestion :P
