### ISSUE TITLE
issue with rei

### ISSUE THREAD

**Issue by milkev** [badasintended/slotlink#4]
when in the crafters gui, REI is completely disabled, though the search bar still appears at the bottom. if this issue lies with rei, my bad, let me know and ill post this issue there.

**Comment by deirn** [comment]
I think this issue appears on any spinnery gui
https://github.com/vini2003/Shest/issues/3

**Comment by deirn** [comment]
you may need to use latest rei, idk

**Comment by milkev** [comment]
it does load in rei, however the rei crafting crashes the game

**Comment by deirn** [comment]
bruh

**Comment by milkev** [comment]
upon a little bit of farther inspection, it appears closing the rei window is what crashes it? whenever i close out of the recipes window it crashes.

**Comment by deirn** [comment]
hmm let's move to #11, its a bit nicer there :P
