### ISSUE TITLE
Set different sort by default

### ISSUE THREAD

**Issue by TKaemp** [badasintended/slotlink#42]
I'd love to use "Sort by Count" as default, meaning whenever I open the Network, it should sort by count automatically instead of "Sort by Name".

For example, instead of left clicking, right click to change the sorting to a new default. You can differentiate whether the icon for the sort is pressed down (usual left click) or normal (your default).

Also side note: Name sort descending / Identifier sort descending would be a cool feature too.

**Comment by deirn** [comment]
yeah, it used to save the sort but I broke it haha. the descending is cool, ill add it
