### ISSUE TITLE
crash on dedicated server

### ISSUE THREAD

**Issue by calloatti** [badasintended/slotlink#43]
**Setup**
- Minecraft: 1.16.1
- Fabric API: fabric-api-0.17.0+build.386-1.16.1.jar
- slotlink: slotlink-1.1.6+minecraft-1.16.1.jar
- related mod: VERSION

**Problem**
crashes on server
https://paste.ee/p/MrEyN

**Reproduction**
Try to use in on a server, it crashes

**Remarks**
_Additional info lies here_

**Comment by deirn** [comment]
fixed with https://github.com/badasintended/Spinnery/commit/0c9921885d26d22c1bb1ec19077f17418f4b6682
will close until shipped
