### ISSUE TITLE
Can't open via Lan

### ISSUE THREAD

**Issue by Ivo-M-Rocha** [badasintended/slotlink#45]
I'm playing with a friend via Lan and when he Tabs out of the window or sometimes just randomly, I can't access the storage request not even using the remotes (He is the host of the server).

**Comment by deirn** [comment]
can you tell me more detail? it maybe related to #43

**Comment by Ivo-M-Rocha** [comment]
Some times, when I'm playing in the Lan server, I'm unable to open the storage, by what my friend told me some of these times he was on another tabs, but some times, while he's still in the game, this bug persists. Apart from these, everything is smooth, without any crash or anything.

**Comment by deirn** [comment]
no error or something?

**Comment by Ivo-M-Rocha** [comment]
Nope, completely nothing, it just doesn't open

**Comment by Ivo-M-Rocha** [comment]
I just noticed that if he's in the system, mostly of the times I cannot open it either

**Comment by deirn** [comment]
shouldn't happen in 2.0 since it uses vanilla system now
