### ISSUE TITLE
Bug with the multi dimensional remote.

### ISSUE THREAD

**Issue by Eisenyx** [badasintended/slotlink#46]
**Setup**
- Minecraft: 1.16 versions
- Fabric API: 1.16 versions
- slotlink: 1.16 versions
- related mod: slotlink

**Problem**
This happens in the modpack "All of Fabric 3".

There is a bug with the multi dimensional remote. When I was exploring the nether or the end, none of the things I put into my storage using the multi dimensional remote were there. They were all gone.
 
**Reproduction**
There is a video link of me recreating the bug. You can clearly see the bug if you look at the number of the items that I show. 
https://streamable.com/pan7qs

**Remarks**
If I take an item from my storage and put it in again when I am in the nether or the end, there is no bug. But the items that are obtained and put into the storage in the nether or the end creates this bug.

**Comment by deirn** [comment]
already reported in #40
also it's fixed in dev but there's another issue with delay
