### ISSUE TITLE
Crafting grid GUI not up to date

### ISSUE THREAD

**Issue by Adirelle** [badasintended/slotlink#47]
**Setup**
- Minecraft: 1.16.2
- Fabric API: 0.19.0+build.398-1.16
- slotlink: 1.1.6+minecraft-1.16.2

**Problem**

I have two (possibility unrelated) issues with the crafting grid GUI.

1. Sometimes, there are "ghost" items on the crafting grid: I cannot see them yet they are there, and mess with recipes.  E.g. a slot contains an item, that I can grab with LMB, but it displays an empty slot. 
2. Other times, when selecting a recipe using REI and crafting the item, the result shown by the mouse pointer is the one of a previous recipe but when I put the hold item in my inventory, it "changes" to the good one.  E.g. if I use REI to select and craft 3 redstone torchs then I use REI to select and craft a redstone comparator then the mouse pointer holds a redstone torch instead of a redstone comparator.

**Reproduction**

Not really sure how it happens.

1. I think closing the GUI with items still on the grid cause the "ghost item" issue.
2. I think this happens when crafting several recipes in a row with REI.

**Remarks**

It happens with both the Request Storage and the Remotes. It also occurs since several versions. This is a minor bug as using the arrow to clear the crafting grid fixes it.

**Comment by deirn** [comment]
it should be gone in 2.0 since I use vanilla system
