### ISSUE TITLE
crash on 1.16.2 server when trying to open gui

### ISSUE THREAD

**Issue by Monster-Zer0** [badasintended/slotlink#49]
**Setup**
- Minecraft: 1.16.2
- Fabric API: Fabric API 0.19.0+build.398-1.16
- slotlink: slotlink 1.1.6+minecraft-1.16.2
- related mod: n/a?

**Problem**
open slotlink ui -> crash
https://hastebin.com/zafagayuci.php

**Reproduction**
have 1.16.2
have slotlink 1.1.6
all the other mods listed in crash report

**Comment by deirn** [comment]
It's the same issue with #43
