### ISSUE TITLE
crafting suggestion

### ISSUE THREAD

**Issue by milkev** [badasintended/slotlink#5]
make items in the crafting grid automatically be replaced with items from the system after crafting.
ie: i put 8 cobblestone in to make a furnace, i craft the furnace, then 8 more cobblestone is automatically put in

**Comment by deirn** [comment]
I have an issue with auto refill and most of the time ended up crafting more than I needed lol
maybe I'll add a button to add stack/redo the last craft or something
what do you think?

**Comment by milkev** [comment]
i think it auto refilling to shift craft a max of one stack, provided the resources are there, would be fine. if you are having a hard time limitting it then a 'readd' last recipe button would also work.

**Comment by deirn** [comment]
sure then, i'll work on it after some break. thanks for your suggestion!

**Comment by deirn** [comment]
@milkev can you try [0.2.3](https://github.com/badasintended/slotlink/releases/tag/slotlink-0.2.3) before I upload it on CF, please?

**Comment by milkev** [comment]
works great!
only thing i noticed is it crafts a stack+1

**Comment by deirn** [comment]
ah, i think i know where to change, I'll fix it tomorrow, thanks
