### ISSUE TITLE
Storage Inventory Bug

### ISSUE THREAD

**Issue by Enoch89** [badasintended/slotlink#50]
**Setup**
- Minecraft: 1.16.1
- Fabric API: 0.17.0
- slotlink: 1.0.3
- related mod: VERSION
-Modpack: All of Fabric 3 1.5.3
-Launcher: Curse/Twitch

**Problem**
When items are stored inside the inventory system, the storage remote UI and the storage request UI show twice the amount of any given item inside the system. When the item is removed, the item amount is the amount that was originally put in. There is no item dupe here, just a UI bug reporting twice the amount of inventory.

**Reproduction**
_Explain how you set up the storage network. Maybe attach some screenshots._

![2020-09-02_16 14 49](https://user-images.githubusercontent.com/7659090/92032150-b7bfb580-ed37-11ea-998e-b09450fa5ae5.png)

![2020-09-02_16 15 00](https://user-images.githubusercontent.com/7659090/92032205-cd34df80-ed37-11ea-8f21-c9bcb2628e32.png)

![2020-09-02_16 15 02](https://user-images.githubusercontent.com/7659090/92032216-d160fd00-ed37-11ea-93e5-100d8a088bc2.png)

**Remarks**
_Additional info lies here_

**Comment by deirn** [comment]
please update, it's 1.2 now :P. it's already fixed
