### ISSUE TITLE
Cannot choose to which block a link/import/export cable must connect

### ISSUE THREAD

**Issue by Adirelle** [badasintended/slotlink#51]
**Setup**
- Minecraft: 1.16.2
- Fabric API: 0.20.1
- slotlink: 1.2

**Problem**
When placing a link cable in a block surrounded by several containers, it always connect to same container, regardless of the direction that the player is facing. According to my tests, sides are prioritized in this order : north > south > east > west

This is quite annoying when you want to plug a given container in a restricted place.

**Reproduction**

Put several chests around a empty place, then place a link cable in the middle. Here is a screenshot with the 16 possible combinations of horizontal directions ; top is north. In cases with more than one chest, you cannot place the link cable in any other way that the one pictured below.

![2020-09-10_15 04 29](https://user-images.githubusercontent.com/24633/92732928-60dd6000-f377-11ea-9d91-9ac59cde91e6.png)

**Remarks**
I have not tested up and down directions, but I guess it is the same.
This might be related to #48 .

**Comment by deirn** [comment]
yeah it's actually designed to be like that since I'm not sure how to check if the inventory already has a cable connected to it
https://github.com/badasintended/slotlink/blob/e7624b189aada6a20be37897b9cb4912f6525dcd/src/main/kotlin/badasintended/slotlink/block/ConnectorCableBlock.kt#L25-L56

it seems like #48 only happened on the 1.16.1 version, maybe because I merged it wrong.

**Comment by Adirelle** [comment]
> yeah it's actually designed to be like that since I'm not sure how to check if the inventory already has a cable connected to it

Well, if one can choose to which inventory it should connect, multi-connecting a single inventory is not really your problem ; just add a warning somewhere in the wiki.

> ah sh*t a brilliant idea just pop out i'll work on changing it soon

I am eager to see that idea.

**Comment by deirn** [comment]
now it will connect to the right-clicked block first before searching around for inventory, kinda like how you place a lever it sticks to the block side.

omg im so smart /s
