### ISSUE TITLE
Optional NBT filtering for cables ?

### ISSUE THREAD

**Issue by Adirelle** [badasintended/slotlink#53]
**Setup**
- Minecraft: 1.16.2
- Fabric API: 0.20.1+build.401-1.16
- slotlink: 1.2.2
- related mod: TechReborn 1.16-3.5.3+build.115

**Problem**
Cables with filters cannot differentiate items based on NBT data.

**Reproduction**
1. Store different types of TechReborn cells in your network containers.
2. Connect an export cable to a chest.
3. Configure the cable filter to only allow one type of cell, say Hydrogen Cell.
4. Look how all cells are exported to the chest, not only the hydrogen ones.

**Remarks**
Ignoring NBT is also useful in some cases, like storing all enchanted books/items in a specific container, so taking NBT into account should be optional. This could be added as either a cable option or as "advanced" types of cables to craft (in the second case, I have some suggestions of "advanced" features).

**Comment by deirn** [comment]
#41 yep, there's no nbt filter _yet_. My current idea is to make an anonymous `Inventory` object with filtered transfer handling, 
which seems like a good idea
