### ISSUE TITLE
Stockpile barrels freeze the game

### ISSUE THREAD

**Issue by dzwdz** [badasintended/slotlink#55]
**Setup**
- Minecraft: 1.16.1
- Fabric API: 0.17.0
- slotlink: 1.2.2 (build from #54)
- related mod: stockpile 1.1.5

**Problem**
Using a Storage Request that's connected to a network with a max upgraded stockpile barrel makes the server freeze, using up all available memory.

**Reproduction**
The barrel had 6x double multiplers, for a total of ~130000 slots of capacity, it was filled with ~40k items.

**Remarks**
The network also has an import cable - it still works as excepted without causing any lag.

**Comment by deirn** [comment]
that's my bad, it's the wrong variable :P 
also since the workaround is making one stack as one slot, it'll slows down the tps the higher the upgrade are.
i think 2<sup>6</sup> (2048 slots) is fine but watchout if you use the 4x multiplier
