### ISSUE TITLE
Search bar doesn't show it's text

### ISSUE THREAD

**Issue by milkev** [badasintended/slotlink#6]
search bar doesnt work, put some cobblestone in a test system, attempted to search for it, and as soon as i started typing nothing came up.

**Comment by deirn** [comment]
not testing in 1.16 sure backfired rly hard

**Comment by deirn** [comment]
alright, search *function* should be working on 0.2.2
the invisible text, seems like spinnery issue

**Comment by layou233** [comment]
Also a bug in search bar, if i type some special language text in it, like Chinese, search doesn't work.
But then if i type any other text next and then delete these text, it will work as usual. XD just strange. It may cant detect chinese input.(havent try Japanese yet)

**Comment by deirn** [comment]
i wonder if chinese have some sort of whitespace character or something...
ill investigate this, thanks

**Comment by deirn** [comment]
closed this because the main issue is fixed, will create a new issue for Chinese characters
