### ISSUE TITLE
Allow crafting with Charm chests

### ISSUE THREAD

**Issue by alxpettit** [badasintended/slotlink#61]
Currently the chests added by [Charm](https://github.com/svenhjol/Charm) don't work with Slotlink.

**Comment by deirn** [comment]
just tried it and it works though? mind telling me your setup?
![2020-11-01_14 05 27](https://user-images.githubusercontent.com/21150434/97796990-5e96d400-1c4b-11eb-83ab-515dfaf546cc.png)

**Comment by alxpettit** [comment]
No, sorry for the syntactic ambiguity. I mean that the chests can't be used to craft items from slotlink.

**Comment by deirn** [comment]
ah, i guess charm doesn't add its items to `c:chest` (or `c:chests` lol) tag like other mods do in https://fabricmc.net/wiki/tutorial:tags
I think I can make a PR to charm to add that

**Comment by deirn** [comment]
i added charm chests to the tag here for now

**Comment by alxpettit** [comment]
cool thx :3
