### ISSUE TITLE
Storage request gui is empty regardless of connections

### ISSUE THREAD

**Issue by systemshaper** [badasintended/slotlink#62]
**Setup**
- Minecraft: 1.16.3
- Fabric API: fabric-api-0.20.1+build.401-1.16.jar
- forge: 33.0.61
- slotlink: slotlink-2.0.0+1.16.3.jar
- related mod: modpack Craft to Exile [Harmony] version 1.0

**Problem**
_State your problem here._
I tried a number of different setups including the exact setups shown on the wiki getting started page, but my Storage Request gui is always empty. I can right click on the Network Master and it identifies the attached storages. I do receive a warning in the console each time I right click and open the storage request block, linked below.

console warning: https://pastebin.pl/view/d55ef1a1

**Reproduction**
screenshot of one of the setups I tried, among many:
![2020-10-30_22 32 14](https://user-images.githubusercontent.com/59181708/97770444-56328200-1b01-11eb-84d3-07d314e60dd5.png)

**Comment by deirn** [comment]
that's a pretty cursed error, can you send a full log? that one only shows the error trace

**Comment by systemshaper** [comment]
Sure! Here is the latest.log file, is that any more helpful?
[latest.log](https://github.com/badasintended/slotlink/files/5469126/latest.log)

**Comment by systemshaper** [comment]
Oh that is just the client log. And here is the server's log:
[2020-10-30-2.log](https://github.com/badasintended/slotlink/files/5469194/2020-10-30-2.log)

**Comment by deirn** [comment]
![mojank](https://user-images.githubusercontent.com/21150434/97782850-82640680-1bc6-11eb-9d7c-d3e819a745fd.png)

**Comment by systemshaper** [comment]
Thank you! That did it sure enough.
