### ISSUE TITLE
Make it possible to craft the multi dim remote with the dragon egg

### ISSUE THREAD

**Issue by alxpettit** [badasintended/slotlink#64]
Would be a bit cool for people who have already fought the dragon and didn't bring glass bottles with them :P

**Comment by deirn** [comment]
im not sure i want to use my one and only dragon egg to make remote :P
I made that cursed recipe so slotlink won't be too OP and kill backpack mods

**Comment by alxpettit** [comment]
Don't you get another dragon egg if you resummon the dragon? Seems like an ok option.

**Comment by deirn** [comment]
i don't think so, you can only get one per world

**Comment by alxpettit** [comment]
:O D:

**Comment by deirn** [comment]
well yeah, im closing this issue
