### ISSUE TITLE
Make the font Smaller on the item count

### ISSUE THREAD

**Issue by Unseenfury** [badasintended/slotlink#7]
So Basically, the font is soo big that i sometimes get confused on some of the numbers on the items inside the Storage Request Gui
If possible reduce the font size on the item counter

**Comment by deirn** [comment]
done, will be published alongside #5 
![2020-07-02_18 09 40](https://user-images.githubusercontent.com/21150434/86352279-bf0f0800-bc8f-11ea-9bf4-c52e210c940f.png)

**Comment by deirn** [comment]
by implementing this i also fixed the annoying offset which is nice lol
