### ISSUE TITLE
Bar to indicate storage capacity

### ISSUE THREAD

**Issue by Laialot** [badasintended/slotlink#70]
a bar or some type of indicator that shows how much of the current max capacity is currently being used, to know when it's proper to add more chests, either in the GUI or in the info shown when right-clicking the network master block

**Comment by deirn** [comment]
added number that shows empty slot available, hover it to show the filled/total slots
![2020-12-16_14 49 19](https://user-images.githubusercontent.com/21150434/102319743-ecd1da00-3fad-11eb-9c57-205e48e34175.png)
