### ISSUE TITLE
Crash using the mod "slotlink" when going from "Age of Exile 1.16.3-1.7.7" to "Age of Exile 1.16.3-1.7.10" in Adventure Pack modpack

### ISSUE THREAD

**Issue by Inewbz** [badasintended/slotlink#71]
**Setup**
- Minecraft: 1.16.4
- Fabric API: 0.29.3+1.16
- slotlink: 2.2.0+1.16.4
- Age of Exile: 1.16.3-1.7.10

**Problem**
Opening the slotlink storage interface (via remote or block) instantly crashes single player and server

**Reproduction**
Opening the slotlink storage interface immediately crashes single player and server

**Remarks**
I understand this is being used in a modpack so it might be other issues compounded, but when using the older version I do not crash with slotlink. However, when using the new version, opening up the slotlink storage instantly causes a crash with an exception/crash to do with null ticks both in singleplayer and on my server.

**Comment by deirn** [comment]
please send the log

**Comment by Inewbz** [comment]
> please send the log

[crash-2021-02-05_16.17.39-server.txt](https://github.com/badasintended/slotlink/files/5931627/crash-2021-02-05_16.17.39-server.txt)

**Comment by deirn** [comment]
It's NBT Crafting bug https://github.com/Siphalor/nbt-crafting/issues/64
