### ISSUE TITLE
Server crash when open re

### ISSUE THREAD

**Issue by ahkui** [badasintended/slotlink#72]
**Setup**
- Minecraft: 1.16.5
- Fabric API: 0.30.0
- slotlink: 2.2.0

**Problem**
[crash-2021-02-08_17.59.00-server.txt](https://github.com/badasintended/slotlink/files/5945754/crash-2021-02-08_17.59.00-server.txt)

**Comment by deirn** [comment]
Same error as #71, update NBT Crafting.
https://github.com/Siphalor/nbt-crafting/issues/64
