### ISSUE TITLE
[QUESTION] Expanded Storage

### ISSUE THREAD

**Issue by srnyx** [badasintended/slotlink#75]
Does this work with Expanded Storage? If, so are there any known bugs with it?
_Also, could you add a Question template when opening an issue (I just realized you can open blank issues without a selected template, should've done that instead of choosing Enhancement, sorry!)?_

**Comment by deirn** [comment]
it kinda works... but people said that it'll show double the number of items if you connect to both sides of double chest since I only check for vanilla double chest. there's also #48 that sometimes happen

**Comment by srnyx** [comment]
> it kinda works... but people said that it'll show double the number of items if you connect to both sides of double chest since I only check for vanilla double chest. there's also #48 that sometimes happen

Alright, thank you!
