### ISSUE TITLE
Ability to disable crafting table and REI search

### ISSUE THREAD

**Issue by srnyx** [badasintended/slotlink#77]
It'd be great if there were client or server options to disable the crafting table and the REI auto-search thing when using the storage request remote.

The crafting table takes up most of the screen (at least on my monitor). It's also completely broken (this is not slotlink's fault, another mod breaks any sort of inventory crafting [crafting table is unaffected], I'm just too lazy to figure out what mod it is).

I'm not sure if the REI auto-search thing is a bug or not, but whenever I search for something in the storage request remote, it also searches in REI. It'd be great if that could be disabled.

**Comment by deirn** [comment]
![2021-05-05_11 36 10](https://user-images.githubusercontent.com/21150434/117097552-2907aa80-ad96-11eb-8856-15adedc6dc9b.png)
