### ISSUE TITLE
Part of bottom row invisible

### ISSUE THREAD

**Issue by srnyx** [badasintended/slotlink#83]
**Setup**
- Minecraft: 1.16.5
- Fabric API: 0.34.2
- slotlink: 2.4.0

**Problem**
A few of the bottom slots in the bottom row of storage request doesn't show any items.
![img](https://cdn.tixte.com/uploads/img.srnyx.xyz/koq5o7q809a.png)

**Comment by deirn** [comment]
this is probably caused by different versions like #84

**Comment by srnyx** [comment]
> this is probably caused by different versions like #84

Yep, it was.
Also, what does Auto Focus Search Bar do?

**Comment by deirn** [comment]
the search bar will get focused when you open if that is enabled, saves like one click :P
