### ISSUE TITLE
Can't get items out of storage

### ISSUE THREAD

**Issue by srnyx** [badasintended/slotlink#84]
**Setup**
- Minecraft: 1.16.5
- Fabric API: 0.34.2
- slotlink: 2.4.0

**Problem**
I can't get any items out of storage using a remote.
I also can't open the storage via the Storage Request block.

**Comment by deirn** [comment]
are you playing on a server?

**Comment by srnyx** [comment]
> are you playing on a server?

Yes

**Comment by deirn** [comment]
is the server has the same version of slotlink?

**Comment by srnyx** [comment]
> is the server has the same version of slotlink?

Oh, shoot, apparently I forgot to follow the mod on CurseForge so I never updated the mod on the server.
Thank you!
