### ISSUE TITLE
Open cable filter gui will cause game crash 

### ISSUE THREAD

**Issue by StarskyXIII** [badasintended/slotlink#87]
**Setup**
- Minecraft: 1.17
- Fabric API: 0.34.10
- slotlink: 3.0.1
- REI: 6.0.249-alpha

**Problem**
When I open the Filter Gui of any Cable, it will cause game crash.
But when I Uninstall REI ,it works fine.
Crash report: https://pastebin.com/vY7NG75F

**Comment by deirn** [comment]
fixed in 3.0.2

**Comment by StarskyXIII** [comment]
Thank you for quick fix
