### ISSUE TITLE
[Server] Network Master Forgets Network on Chunk Reload

### ISSUE THREAD

**Issue by milkev** [badasintended/slotlink#91]
**Setup**
- Minecraft: 1.17
- Fabric API:  0.35.2
- slotlink: 3.0.2
- related mod: Dedicated Server

**Problem**
Upon reloading the chunk the network master is in, it forgets the network it is attached to, despite being visually connected.

**Reproduction**
1. make a simple network. make sure to do this outside of chunk loaded areas such as spawn chunks
2. right click network master to make sure its recognizing its storage space
3. go to the nether and back, or far enough away to unload the chunks, and back
4. right click network master, it will say that there is no storage connected to it
5. break and replace network master, it will recognize the network again. I had one occassion where it only recognized half the network after being replaced, despite my entire settup being within one chunk, but was unable to reproduce that behaviour.
![2021-06-20_06 56 15](https://user-images.githubusercontent.com/22010128/122675444-af394e00-d196-11eb-9a25-c9d527d1bdd3.png)
*I tested this with and without other mods, it made no difference

**Remarks**
Am on a dedicated server.
Is the chunk the network master is in supposed to be chunkloaded? the network did not break when it was in chunkloaded chunks, though I did not test with restarting the server.

**Comment by deirn** [comment]
can you send me your `world/data/slotlink.dat`? it should contain the network data

**Comment by milkev** [comment]
in its broken state or?

**Comment by deirn** [comment]
ah yes, broken state

**Comment by milkev** [comment]
sorry, kind of a dumb question to ask ,-,

github doesnt accept .dat files, so i uploaded it to my google drive, should be able to download it from there with just the link
[](https://drive.google.com/file/d/1TaXkY4EhSm7qI0QBI7grSMSoa6y7E31p/view?usp=sharing )
