### ISSUE TITLE
[1.17] Right clicking on Export/ Import cables causes game to crash

### ISSUE THREAD

**Issue by KingTarunjot** [badasintended/slotlink#93]
**Setup**
- Minecraft: 1.17
- Fabric API: 0.36.0
- slotlink: latest/ 1.17
- related mod: Using Valhelsia Fabric Modpack (https://www.curseforge.com/minecraft/modpacks/valhelsia-fabric) but added slotlink mod in.

**Problem**
Whenever a player right clicks on export or import cable the game crashes due to Rendering Window error.
Crash report: https://pastebin.com/2SJsHsp2
**Reproduction**
Just place Import or export cable anywhere does not have to be connected to anything

**Remarks**
I tried to use import/ export cable after removing Inventory Sorter mod but that did not fix crash.

**Comment by deirn** [comment]
> latest

> 3.0.1

Update.
