### ISSUE TITLE
[Bug/Question] Is the FPS loss while in the interface fixable?

### ISSUE THREAD

**Issue by Desempregago** [badasintended/slotlink#95]
https://user-images.githubusercontent.com/14002834/127372690-ff00d744-ecec-434e-bfd9-0c16f01ba738.mp4

slotlink v3.0.5

**Comment by deirn** [comment]
I'm afraid not, it's the issue with vanilla rendering. You can notice slight fps decrease on vanilla creative search aswell (use alt+f3 to show the graph).

**Comment by deirn** [comment]
Well turns out using ninepatch is pretty expensive 😭. It's probably because of my bad implementation though. Anyway, from https://github.com/badasintended/slotlink/commit/09678800020a74abfb8ebecb27d0d851db34f6f1 now it uses actual 256x256 textures and it's better now
