### ISSUE TITLE
Game crashes when clicking favorite from REI

### ISSUE THREAD

**Issue by johannesmateboer** [badasintended/slotlink#96]
**Setup**
- Minecraft: 1.17.1
- Fabric API: 0.11.6
- slotlink: 3.0.5
- related mod: REI 6.0.264

**Problem**
When clicking a favorite in REI, while having the slotlink-GUI open, the game crashes.
Crash report: https://pastebin.com/9Q0WQLxg

**Reproduction**
Add favorite to REI, open slotlink GUI, click favorite with mouse

**Remarks**

**Comment by deirn** [comment]
I can't seem to reproduce the CME, but can you try this jar? 
[slotlink-local.zip](https://github.com/badasintended/slotlink/files/6912234/slotlink-local.zip)

**Comment by johannesmateboer** [comment]
Tried it in the same Minecraft-instance: I cannot get it to fail/crash anymore.
